### ISSUE TITLE
No module "threatingestor.extras.webapp"

### ISSUE THREAD

**Issue by deadbits** [InQuest/ThreatIngestor#75]
Just tried a quick test run following the tutorial on the ReadTheDocs page and hit an exception trying to get the minimal web UI.

Any ideas on something I'm missing?

```
» cat inquest-blog-sqlite.yml                                     [11:28:39]
general:
    daemon: false
    sleep: 900
    state_path: state.db

sources:
  - name: inquest-blog
    # Read from the InQuest blog.
    module: rss
    url: http://feeds.feedburner.com/Inquestblog?format=xml
    feed_type: messy

operators:
  - name: sqlite-artifacts
    # Write artifacts to a SQLite database.
    module: sqlite
    filename: artifacts.db
```

```
» threatingestor inquest-blog-sqlite.yml                          [11:28:41]
2019-09-05 11:28:46.451 | INFO     | threatingestor:<module>:12 - Notifiers is not installed.
2019-09-05 11:28:46.495 | DEBUG    | threatingestor:__init__:30 - Reading config from 'inquest-blog-sqlite.yml'
2019-09-05 11:28:46.498 | DEBUG    | threatingestor:__init__:51 - Log handler reconfigured
2019-09-05 11:28:46.500 | DEBUG    | threatingestor:__init__:63 - Opening state database 'state.db'
2019-09-05 11:28:46.501 | DEBUG    | threatingestor:__init__:72 - Initializing sources
2019-09-05 11:28:46.501 | DEBUG    | threatingestor.config:sources:113 - Found source 'inquest-blog'
2019-09-05 11:28:46.608 | DEBUG    | threatingestor.config:sources:116 - Found 1 total sources
2019-09-05 11:28:46.608 | DEBUG    | threatingestor:__init__:76 - Initializing operators
2019-09-05 11:28:46.608 | DEBUG    | threatingestor.config:operators:160 - Found operator 'sqlite-artifacts'
2019-09-05 11:28:46.609 | DEBUG    | threatingestor.config:operators:163 - Found 1 total operators
2019-09-05 11:28:46.609 | DEBUG    | threatingestor:run:92 - Running once, to completion
2019-09-05 11:28:46.609 | DEBUG    | threatingestor:run_once:104 - Running source 'inquest-blog'
2019-09-05 11:28:46.610 | DEBUG    | threatingestor.state:get_state:35 - Getting state for 'inquest-blog'
2019-09-05 11:28:46.861 | DEBUG    | threatingestor.state:save_state:28 - Updating state for 'inquest-blog' to 'None'
2019-09-05 11:28:46.863 | DEBUG    | threatingestor:run_once:119 - Processing 0 artifacts from source 'inquest-blog' with operator 'sqlite-artifacts'
2019-09-05 11:28:46.863 | NOTIFY   | threatingestor:run_once:137 - New artifacts: {}
```

```
aswanda:threatingestor/ » ls -al artifacts.db                                             [11:28:47]
-rw-r--r-- 1 aswanda 53248 Sep  5 11:27 artifacts.db
```

```
aswanda:threatingestor/ » hug -m threatingestor.extras.wabapp                             [11:29:00]
2019-09-05 11:29:06.909 | INFO     | threatingestor:<module>:12 - Notifiers is not installed.
Traceback (most recent call last):
  File "/usr/local/bin/hug", line 10, in <module>
    sys.exit(development_runner.hug.interface.cli())
  File "/usr/local/lib/python3.7/site-packages/hug/interface.py", line 649, in __call__
    raise exception
  File "/usr/local/lib/python3.7/site-packages/hug/interface.py", line 645, in __call__
    result = self.output(self.interface(**pass_to_function), context)
  File "/usr/local/lib/python3.7/site-packages/hug/interface.py", line 129, in __call__
    return __hug_internal_self._function(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/hug/development_runner.py", line 68, in hug
    api_module = importlib.import_module(module)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'threatingestor.extras.wabapp'
```

**Comment by deandrehall** [comment]
Looks like there was just a minor typo in the command you ran
"threatingestor.extras.wabapp" -> "threatingestor.extras.webapp"

**Comment by deadbits** [comment]
bahhh i am a fool!
